language: node_js
node_js:
- '0.12'
- '0.10'
env:
  global:
    secure: K2W5iLgOQuctIi+9qpwyjZbe+FcGdacZXoz6s/g6nse3IvGe7zgswyekUpgtSXmvF+mxnFtbXvCkP78YFskKvU5W7FvU5WHS8a0vs8LeMjubdDWCzmhDF6/sIKq5fSp2DR98gSOcNcTOmpqBUb01wgvBGbcYvabWw1TCa16liCFNw3QB9/7fpYyFTvU7eVua0Edpb7yXme56JxjG7hG55JUPR1hgjE7xMQFbliHFfTALw//HBF/hV1lgk/tOga6/E8bwW2yZM9KWX63Bi7cffrBHzPHL1oL4QhpDb2D6NJDPAADhuPzn+AgIex1iivIHQxWKuaibhYxJX12+XVAbBqwTs9v/azPYNC3FBFdf76n17kSCHiZuW325DeCG+wUPUN8ux4wzMTEmx6urHvzwJ+8mdAcSUY83pmCx3f/m6ncn396WDs1QXGsQPchaiMrsE9egUgdq9KUEtNCRopQp7+zOGoAtlSxqZDUqMvR5UfYV+qUWSYwM/8oWGjoDoIz0kD6p1VBOtQUvUS0+8WlGHRcqdLJjy8KIGi9bAF8CPRdd0UgMYR5afd11qr38I1qpNXpVL/Mm+2f8aIlkxF5gm3+VVhf3qSjbofU7/U+AoAx4vaXIc7kYoylREDOlsgCEBxpSByLKDr37NQN/N7+p614kAl5cGa4VikexCxPUC+Y=
